language: node_js
node_js:
 - "stable"
cache: 
  directories: 
    - "node_modules" 
install:
  - npm install   
 

services: 
   - postgresql 

deploy:
   provider: heroku
   api_key:
      secure: "76cf78f1-d836-4dbf-9dfc-e53bb607d749"
env: 
   global: 
   - NODE_ENV=development


before_script:
 - npm install -g sequelize-cli
 - sequelize db:migrate
    
script: 
   - npm run test



 
 
